name: book_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/gradient.png
    - images/sci_fi.png
    - images/profile.png
    - images/pillar.png
    - images/audio_visualizer.png
    - images/books/book1.png
    - images/books/book2.png
    - images/books/book3.png
    - images/books/book4.png
    - images/books/book5.png
    - images/books/book6.png
    - images/books/book7.png
    - images/books/book8.png
    - images/books/book9.png